blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ è³ªå•ãƒ»é›‘è«‡ç”¨ã‚¹ãƒ¬ãƒƒãƒ‰
    url: https://github.com/${{ github.repository }}/discussions
    about: é–‹ç™ºã«é–¢ã™ã‚‹è³ªå•ãƒ»é›‘è«‡ã¯ã“ã¡ã‚‰ã¸
